all:
	@(cd panache && $(MAKE))
	@(cd lio && $(MAKE))
	@(cd actions && $(MAKE))

install:
	@(cd panache && $(MAKE) install)
	@(cd lio && $(MAKE) install)
	@(cd actions && $(MAKE) install)

clean:
	@(cd panache && $(MAKE) clean)
	@(cd lio && $(MAKE) clean)
	@(cd actions && $(MAKE) clean)