all:

install:
	@(cd theme && $(MAKE) install)

	@install -d -m755 $(DESTDIR)/usr/share/logram/themes/default/wallpapers/
	@cp wallpapers/* $(DESTDIR)/usr/share/logram/themes/default/wallpapers/

clean:

