CONFIG += plugin
TEMPLATE = lib
INCLUDEPATH += ../../include /usr/include/logram
SOURCES += Search.cpp
HEADERS += Search.h
TARGET = Search
RESOURCES += QRessource.qrc
DESTDIR = ../..
DEPENDPATH += .
